### ISSUE TITLE
Currency Syncs across Game Saves [BUG]

### ISSUE THREAD

**Issue by krebork** [Bit-Studios/Kapitalism#4]
**Describe the bug**
The prompt for choosing your administration type only occurs once - and the funds/admin type persists into new games.

**To Reproduce**
1. New save (exploration/normal settings)
2. Kapitalist Administration type
3. Launch a rocket
4. Revert to pre-launch save (At this point the bug is present as funds have been lost for the rocket launch that has not yet occurred in this save)
5. Try to create new save to get starting funds (No administration prompt and synced funds from previous save)

**Expected behavior**
I would expect for the older save to show the initial 5k starting funds since the rocket never launched, and for the new save file to allow me to pick my administration type again and reset my funds to 5k.

**Screenshots**
![image_2024-04-14_124540699](https://github.com/Bit-Studios/Kapitalism/assets/167018744/7ca3393d-f66b-4a26-b760-a9895623059a)
(Definitely could be mod compatibility)

**Desktop (please complete the following information):**
 - OS: Win11 Home
 - Browser: Opera
 - Version: 0.2.1.0 (Kapitalism 0.0.1)

**Additional context**
I will mess around with save files in folder to attempt to hard reset, as well as trying to reinstall the mod. Currently makes loading the mod gamebreaking as after one launch and reverting I am now softlocked from making any progress across any number of saves.

**Comment by krebork** [comment]
Can confirm that disabling the mod in menu, followed by a restart, followed by enabling the mod, followed by a restart, does allow me to select my admin type with fresh funds on a new save file :)

**Comment by krebork** [comment]
Seems like every save revert bugs the funds at least on my client with listed mods

**Comment by NathanPeake** [comment]
With the revert bug how are you reverting? 
Load Game or Revert to VAB
![image](https://github.com/Bit-Studios/Kapitalism/assets/37817019/acc6656e-e2dc-4d3e-a4a3-ac537d751370)

**Comment by NathanPeake** [comment]
Have fixed:
- choosing your administration type only occurs once
- Revert to VAB does not use buffered save

Will be fixed for 0.0.2:
Load game does not keep previous game state.

Hotfix is being released for the 2 game breaking bugs

**Comment by krebork** [comment]
Prior to the hotfix I was able to replicate it using both a revert to VAB and a load save - will reinstall and keep testing :)

**Comment by NathanPeake** [comment]
Waiting for your tests before I close this issue

load save will be fixed in 0.0.2

**Comment by krebork** [comment]
Revert load seems to be working as intended - great work boss
